import Link from "next/link";
import { COMPANY, SERVICES, BRANDS, AREAS, SERVICE_VISUALS } from "../lib/data";
import { ServiceForm } from "../components/ServiceForm";
import { Reveal } from "../components/Reveal";
import { ServiceVisual } from "../components/ServiceVisual";

const problems=["Çalışmıyor","Soğutmuyor","Su almıyor","Su boşaltmıyor","Ses yapıyor","Isıtmıyor","Hata kodu veriyor","Su kaçırıyor"];
const appliances=[["Çamaşır Makinesi","washingMachine"],["Bulaşık Makinesi","dishwasher"],["Buzdolabı","refrigerator"],["Kurutma Makinesi","dryer"],["Fırın","whiteGoods"]] as const;
export default function Home(){return <>
  <section className="hero"><div className="container hero-grid"><Reveal className="hero-copy"><p className="eyebrow">İzmir Teknik Servis</p><h1>Beyaz Eşya, Klima ve Teknik Servis Hizmetleri</h1><p className="lead">Beyaz eşya, klima, kombi, televizyon, ısı pompası ve VRF sistemleri için arıza tespiti, bakım ve onarım hizmeti.</p><div className="actions"><a className="button amber phone-button" href={COMPANY.phoneHref}>☎ Hemen Ara</a><a className="button outline whatsapp-button" href={COMPANY.whatsappUrl}>◉ WhatsApp&apos;tan Yaz</a></div><div className="hero-trust"><span>08:00–19:00 Hizmet</span><span>İzmir&apos;de geniş servis ağı</span><span>Çok markalı özel servis</span></div></Reveal><Reveal variant="fade-left" delay={100} className="hero-visual"><div className="hero-image"><ServiceVisual visual="whiteGoods" priority /></div><div className="floating-card hours"><b>08:00–19:00</b><span>Çalışma Saatleri</span></div><div className="floating-card network"><b>İzmir</b><span>Geniş Servis Ağı</span></div><div className="floating-card private"><b>Özel Servis</b><span>Çok Marka & Model</span></div></Reveal></div></section>
  <section className="trust-strip"><div className="container">{["08:00–19:00","Telefon & WhatsApp","İzmir Servis Bölgeleri","Çok Markalı Özel Servis"].map(x=><span key={x}>✓ {x}</span>)}</div></section>
  <section className="section container"><Reveal><div className="section-heading"><p className="eyebrow">Hizmetlerimiz</p><h2>Cihazınıza uygun teknik destek</h2><p>Ev ve iş yerlerindeki temel cihaz ve sistemler için bağımsız özel teknik servis desteği.</p></div></Reveal><div className="service-grid">{SERVICES.map((s,i)=><Reveal key={s.slug} delay={i*65}><Link href={`/${s.slug}`} className="service-card"><ServiceVisual visual={s.visual as keyof typeof SERVICE_VISUALS}/><div className="service-card-copy"><small>Teknik servis</small><h3>{s.name}</h3><p>{s.description}</p><span>Hizmeti incele <b>→</b></span></div></Link></Reveal>)}</div></section>
  <section className="soft-section"><div className="container"><Reveal><div className="section-heading"><p className="eyebrow">Arıza belirtileri</p><h2>Cihazınızda hangi sorun var?</h2><p>Yaşadığınız sorunu iletin; teknik inceleme sonrası uygun destek planlanır.</p></div></Reveal><div className="chips">{problems.map(p=><a href="#servis-talebi" key={p}><i>+</i>{p}</a>)}</div></div></section>
  <section className="section container editorial"><Reveal variant="fade-right" className="editorial-image"><ServiceVisual visual="washingMachine"/></Reveal><Reveal variant="fade-left"><div><p className="eyebrow">Beyaz eşya</p><h2>Günlük kullanılan cihazlar için servis</h2><p className="lead small">Çamaşır makinesi, bulaşık makinesi, buzdolabı, kurutma makinesi ve fırın için bağımsız teknik servis desteği.</p><Link className="text-link" href="/beyaz-esya-servisi">Beyaz eşya hizmetini incele →</Link></div></Reveal></section>
  <section className="soft-section appliance-showcase"><div className="container"><Reveal><div className="section-heading"><p className="eyebrow">Beyaz eşya servisi</p><h2>Her cihaz için net ve ilgili destek</h2></div></Reveal><div className="appliance-grid">{appliances.map(([name,visual],i)=><Reveal key={name} delay={i*60}><Link href="/beyaz-esya-servisi" className={`appliance-card appliance-${i}`}><ServiceVisual visual={visual}/><span>{name}<b>→</b></span></Link></Reveal>)}</div></div></section>
  <section className="navy-section"><div className="container"><Reveal><div className="section-heading light"><p className="eyebrow">Markalar</p><h2>Birçok marka ve modele özel teknik servis</h2></div><div className="brand-list">{BRANDS.map(x=><span key={x}>{x}</span>)}</div><p className="brand-more">ve diğer birçok marka ve model</p><p className="disclaimer">Ege Bölge Teknik Servis Hizmetleri bağımsız özel teknik servis hizmeti sunmaktadır. Listelenen markaların yetkili servisi değildir.</p></Reveal></div></section>
  <section className="section container"><Reveal><div className="section-heading"><p className="eyebrow">Nasıl çalışır?</p><h2>Servis süreci</h2></div></Reveal><ol className="steps">{[["01","Servis Talebi","Telefon veya WhatsApp üzerinden bize ulaşın."],["02","Arıza Bilgisi","Cihaz ve arıza hakkında temel bilgiler alınır."],["03","Teknik Servis","Uygun servis desteği planlanır."],["04","Kontrol","Bakım veya onarım sonrası cihaz kontrol edilir."]].map((x,i)=><Reveal key={x[0]} delay={i*70}><li><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></li></Reveal>)}</ol></section>
  <section className="premium-cta"><div className="container cta-layout"><Reveal><p className="eyebrow">Kolay iletişim</p><h2>Cihazınız için servis desteğine mi ihtiyacınız var?</h2><p>Telefon veya WhatsApp üzerinden servis talebi oluşturabilirsiniz.</p><div className="actions"><a className="button amber phone-button" href={COMPANY.phoneHref}>☎ {COMPANY.phoneDisplay}</a><a className="button cta-whatsapp" href={COMPANY.whatsappUrl}>WhatsApp&apos;tan Yaz</a></div></Reveal><div className="cta-visual"><ServiceVisual visual="airConditioner"/></div></div></section>
  <section className="soft-section"><div className="container area-layout"><Reveal><div><p className="eyebrow">Hizmet bölgeleri</p><h2>İzmir&apos;de hizmet verdiğimiz bölgeler</h2><p>İzmir genelinde geniş servis ağıyla birçok ilçede hizmet sunuyoruz.</p><Link href="/hizmet-bolgeleri" className="button outline">Tüm Hizmet Bölgelerini Gör</Link></div></Reveal><Reveal variant="fade-left"><div className="area-list">{AREAS.slice(0,10).map(x=><span key={x}>{x}</span>)}</div></Reveal></div><p className="exclusion">Beydağ, Kiraz ve Ödemiş bölgelerinde şu anda servis hizmeti verilmemektedir.</p></section>
  <section className="form-section" id="servis-talebi"><div className="container form-layout"><Reveal><div><p className="eyebrow">Servis talebi</p><h2>Size ulaşabilmemiz için bilgilerinizi bırakın</h2><p>Arızayı hızlıca değerlendirebilmemiz için cihaz türü, marka ve yaşadığınız sorunu bize iletebilirsiniz.</p><a href={COMPANY.whatsappUrl} className="text-link">WhatsApp&apos;tan yazın →</a></div></Reveal><Reveal variant="fade-left"><ServiceForm/></Reveal></div></section>
</>}
