import Image from "next/image";
import { AREAS, COMPANY, SERVICES, SERVICE_VISUALS } from "../lib/data";
import { BrandDirectory } from "../components/BrandDirectory";
import { Reveal } from "../components/Reveal";
import { ServiceVisual } from "../components/ServiceVisual";

const advantages = [["01", "Deneyimli Ekip", "Arızaya uygun teknik destek."], ["02", "Hızlı Yönlendirme", "Telefon ve WhatsApp üzerinden hızlı iletişim."], ["03", "Net Bilgilendirme", "Süreç açıkça paylaşılır."], ["04", "İzmir Geneli", "Birçok ilçede servis desteği."]];
const faq = [["Nasıl iletişime geçebilirim?", "Telefon veya WhatsApp üzerinden cihaz ve ilçe bilginizi paylaşabilirsiniz. E-posta ikincil iletişim seçeneğidir."], ["Hangi cihazlar için hizmet veriyorsunuz?", "Beyaz eşya, klima, kombi, televizyon, ısı pompası ve VRF sistemleri için teknik servis desteği sunuyoruz."], ["İzmir'in hangi bölgelerine hizmet veriyorsunuz?", "Buca, Konak, Karabağlar, Bornova ve diğer listelenen ilçelerde hizmet planlaması yapılmaktadır."], ["Yetkili servis misiniz?", "Hayır. Ege Bölge Teknik Servis Hizmetleri bağımsız özel teknik servistir. Listelenen markaların yetkili servisi değildir."]];

export default function Home() {
  return <>
    <section className="hero hero-photo"><Image className="hero-background" src="/images/hero/teknik-servis-hero.png" alt="Klima ünitesinde bakım yapan teknik servis çalışanı" fill priority sizes="100vw" /><div className="hero-shade" /><div className="container hero-content"><Reveal className="hero-copy"><p className="eyebrow eyebrow-light">İzmir Geneli Teknik Servis</p><h1>Evinizdeki Teknolojiye <em>Güvenilir Servis</em></h1><p className="lead">Beyaz eşya, klima, kombi ve elektronik cihazlarda hızlı teknik destek.</p><div className="actions"><a className="button orange" href={COMPANY.whatsappUrl} target="_blank" rel="noopener noreferrer">WhatsApp&apos;tan Yaz</a><a className="button hero-outline" href={COMPANY.phoneHref}>Hemen Ara</a></div><p className="hero-note">Bağımsız özel teknik servis · {COMPANY.hours}</p></Reveal></div></section>
    <section className="section services-section" id="hizmetler"><div className="container"><Reveal><div className="section-heading centered"><p className="eyebrow">Hizmetlerimiz</p><h2>Hangi cihazlara servis veriyoruz?</h2><p>İhtiyacınız olan hizmeti seçin.</p></div></Reveal><div className="service-grid">{SERVICES.map((service, index) => <Reveal key={service.slug} delay={index * 40}><article className="service-card"><a href={`/${service.slug}`} className="service-card-image" aria-label={`${service.name} sayfasını incele`}><ServiceVisual visual={service.visual as keyof typeof SERVICE_VISUALS} /></a><div className="service-card-copy"><p className="service-card-kicker">Bağımsız özel teknik servis</p><h3><a href={`/${service.slug}`}>{service.name}</a></h3><p>{service.description}</p><a href={COMPANY.whatsappUrl} target="_blank" rel="noopener noreferrer" className="service-card-cta">WhatsApp&apos;tan Ulaşın <b>→</b></a></div></article></Reveal>)}</div></div></section>
    <section className="brands-section"><div className="container"><Reveal><BrandDirectory /></Reveal></div></section>
    <section className="advantage-section"><div className="container advantage-grid">{advantages.map(([number, title, text], index) => <Reveal key={title} delay={index * 55} className="advantage-card"><span className="number-icon">{number}</span><div><h2>{title}</h2><p>{text}</p></div></Reveal>)}</div></section>
    <section className="dark-service-section"><div className="container dark-service-grid"><Reveal className="dark-service-copy"><p className="eyebrow eyebrow-orange">Servis desteği</p><h2>İletişime geçin, size yardımcı olalım.</h2><p>Telefon veya WhatsApp üzerinden cihaz ve ilçe bilginizi paylaşabilirsiniz.</p><ul className="check-list"><li>Telefon ve WhatsApp desteği</li><li>İlçeye göre hızlı planlama</li><li>Bağımsız özel teknik servis</li></ul><div className="actions"><a className="button orange" href={COMPANY.phoneHref}>Hemen Ara</a><a className="text-link light-link" href={COMPANY.whatsappUrl} target="_blank" rel="noopener noreferrer">WhatsApp&apos;tan Ulaşın</a></div></Reveal><Reveal variant="fade-left" className="contact-card contact-card--dark"><p className="form-kicker">İletişim</p><h3>WhatsApp&apos;tan yazın</h3><p>Hızlı iletişim için WhatsApp veya telefon kanalını kullanabilirsiniz.</p><a className="button amber" href={COMPANY.whatsappUrl} target="_blank" rel="noopener noreferrer">WhatsApp</a></Reveal></div></section>
    <section className="area-section" id="hizmet-bolgeleri"><div className="container area-layout"><Reveal><div><p className="eyebrow eyebrow-light">Hizmet Bölgeleri</p><h2>İzmir&apos;in birçok ilçesinde teknik servis desteği</h2><p>Geniş hizmet ağımızla talebinizi ilçenize göre değerlendiriyoruz.</p><a className="button white-outline" href="/hizmet-bolgeleri">Tüm hizmet bölgelerini gör</a></div></Reveal><Reveal variant="fade-left"><div className="area-list">{AREAS.slice(0, 12).map(area => <span key={area}>{area}</span>)}</div></Reveal></div><p className="container area-note">Beydağ, Kiraz ve Ödemiş bölgelerinde şu anda servis hizmeti verilmemektedir.</p></section>
    <section className="faq-section" id="sss"><div className="container faq-layout"><Reveal><div><p className="eyebrow">Sık sorulan sorular</p><h2>Servis süreci hakkında merak edilenler</h2><p>Ek bilgiye ihtiyacınız olduğunda telefon veya WhatsApp üzerinden bize ulaşabilirsiniz.</p></div></Reveal><Reveal variant="fade-left" className="faq-list">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</Reveal></div></section>
  </>;
}
