"use client";
import { useEffect, useState } from "react";
import { COMPANY } from "../lib/data";
import { trackEvent } from "../lib/analytics";

const NAV_ITEMS = [["Ana Sayfa", "/"], ["Hakkımızda", "/hakkimizda"], ["Hizmetlerimiz", "/#hizmetler"], ["Hizmet Bölgeleri", "/#hizmet-bolgeleri"], ["Sık Sorulan Sorular", "/#sss"], ["İletişim", "/iletisim"]] as const;

export function Header() {
  const [open, setOpen] = useState(false);
  const closeMenu = () => setOpen(false);
  useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") closeMenu(); }; document.addEventListener("keydown", onKeyDown); return () => document.removeEventListener("keydown", onKeyDown); }, []);
  useEffect(() => { document.body.classList.toggle("menu-open", open); return () => document.body.classList.remove("menu-open"); }, [open]);
  return <header className="site-header"><div className="topbar"><div className="container topbar-inner"><span>Acil Servis / Hızlı Destek</span><a href={COMPANY.phoneHref} onClick={() => trackEvent("phone_click", { placement: "topbar" })}>{COMPANY.phoneDisplay}</a><a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a><span>{COMPANY.hours}</span></div></div><div className="container header-main"><a className="logo" href="/" onClick={closeMenu}><b>EGE BÖLGE</b><small>Teknik Servis Hizmetleri</small></a><button className="menu" type="button" onClick={() => setOpen(value => !value)} aria-label={open ? "Menüyü kapat" : "Menüyü aç"} aria-expanded={open} aria-controls="main-navigation"><i /><i /><i /></button><nav id="main-navigation" className={open ? "open" : ""} aria-label="Ana menü">{NAV_ITEMS.map(([label, href]) => <a key={label} href={href} onClick={closeMenu}>{label}</a>)}<a className="mobile-nav-call" href={COMPANY.phoneHref} onClick={closeMenu}>Hemen Ara</a></nav><a className="button orange header-cta" href="#servis-talebi">Servis Talebi Oluştur</a></div>{open && <button className="menu-backdrop" type="button" aria-label="Menüyü kapat" onClick={closeMenu} />}</header>;
}

export function Footer() {
  const services = [["Beyaz Eşya Servisi", "/beyaz-esya-servisi"], ["Klima Servisi", "/klima-servisi"], ["Kombi Servisi", "/kombi-servisi"], ["TV Tamiri", "/tv-tamiri"]];
  return <><footer><div className="container footer-grid"><div><div className="logo"><b>EGE BÖLGE</b><small>Teknik Servis Hizmetleri</small></div><p>İzmir&apos;de çok markalı bağımsız özel teknik servis hizmeti.</p><p className="footer-hours">{COMPANY.hours}</p></div><div><h3>Hizmetler</h3>{services.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</div><div><h3>Kurumsal</h3><a href="/hakkimizda">Hakkımızda</a><a href="/#hizmet-bolgeleri">Hizmet Bölgeleri</a><a href="/#sss">Sık Sorulan Sorular</a><a href="/iletisim">İletişim</a></div><div><h3>İletişim</h3><p>{COMPANY.address}</p><a href={COMPANY.phoneHref}>{COMPANY.phoneDisplay}</a><a href={COMPANY.mobileHref}>{COMPANY.mobileDisplay}</a><a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Ege Bölge Teknik Servis Hizmetleri</span><div><a href="/kvkk">KVKK</a><a href="/gizlilik-politikasi">Gizlilik</a><a href="/cerez-politikasi">Çerezler</a></div></div><p className="container disclaimer">Ege Bölge Teknik Servis Hizmetleri bağımsız özel teknik servis hizmeti sunmaktadır. Listelenen markaların yetkili servisi değildir.</p></footer><nav className="mobile-bar" aria-label="Hızlı iletişim"><a className="mobile-action mobile-call" href={COMPANY.phoneHref} onClick={() => trackEvent("phone_click", { placement: "mobile_sticky" })}><span>☎</span>Ara</a><a className="mobile-action mobile-whatsapp" href={COMPANY.whatsappUrl} onClick={() => trackEvent("whatsapp_click", { placement: "mobile_sticky" })}><span>◔</span>WhatsApp</a><a className="mobile-action mobile-request" href="#servis-talebi"><span>＋</span>Talep</a></nav></>;
}
